services:
    mongo:
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017
        volumes:
            - mongo_data:/data/db

    golang-connectors:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - MONGO_URI=mongodb://mongo:27017
        env_file:
            - .env
        ports:
            - 9090:9090
        depends_on:
            - mongo

    react-app:
        build:
            context: ../vendors/react-vendor/
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - golang-connectors
    
    # restore:
    #     image: mongo:latest
    #     volumes:
    #         - ./backup:/backup
    #     depends_on:
    #         - mongo
    #     entrypoint: ["bash", "./backup/restore.sh", "./backup/files/СЮДА ВСТАВИТЬ НАЗВАНИЕ БЕКАПА"]

    backup_cron:
        build:
            context: ./backup
            dockerfile: Dockerfile
        depends_on:
            - mongo
        volumes:
            - ./backup:/backup
volumes:
    mongo_data: